on:
  push:
    branches-ignore:
      - 'gh-pages'
    tags-ignore:
      - '*'
  workflow_dispatch:
env:
  GH_TOKEN_DISPATCH: ${{ secrets.GH_TOKEN_DISPATCH }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew check assemble --continue
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            build/libs/*.jar